import { CONTEXT_PROCESSING_CONTRACT_VERSION } from './context-processing-contracts.js';

export const CONTEXT_PROCESSING_PIPELINE_VERSION = 'context-processing-pipeline-v1';
export const CONTEXT_PROCESSING_PARSER_VERSION = CONTEXT_PROCESSING_CONTRACT_VERSION;
export const CONTEXT_PROCESSING_CONCEPT_LEXICON_VERSION = 'concept-lexicon-v1';
export const CONTEXT_PROCESSING_SEMANTIC_CLASSIFIER_VERSION = 'semantic-classifier-v1';
export const CONTEXT_PROCESSING_NOISE_POLICY_VERSION = 'noise-policy-v1';
export const CONTEXT_PROCESSING_SUMMARY_PLANNER_VERSION = 'summary-planner-v1';
export const CONTEXT_PROCESSING_NODE_MATERIALIZER_VERSION = 'semantic-node-materializer-v1';

export const CONTEXT_PROCESSING_VERSIONS = {
  pipeline: CONTEXT_PROCESSING_PIPELINE_VERSION,
  parser: CONTEXT_PROCESSING_PARSER_VERSION,
  conceptLexicon: CONTEXT_PROCESSING_CONCEPT_LEXICON_VERSION,
  semanticClassifier: CONTEXT_PROCESSING_SEMANTIC_CLASSIFIER_VERSION,
  noisePolicy: CONTEXT_PROCESSING_NOISE_POLICY_VERSION,
  summaryPlanner: CONTEXT_PROCESSING_SUMMARY_PLANNER_VERSION,
  nodeMaterializer: CONTEXT_PROCESSING_NODE_MATERIALIZER_VERSION
} as const;
