export const RUNTIME_API_BOUNDARY = [
    { name: 'bootstrap', surface: 'runtime_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'ingest', surface: 'runtime_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'ingestBatch', surface: 'runtime_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'afterTurn', surface: 'runtime_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'assemble', surface: 'runtime_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact', surface: 'runtime_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false }
];
export const DEBUG_API_BOUNDARY = [
    { name: 'compact-context.health', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.ingest_context', surface: 'debug_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.compile_context', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.create_checkpoint', surface: 'debug_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.query_nodes', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.query_edges', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.get_latest_checkpoint', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.list_checkpoints', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.crystallize_skills', surface: 'debug_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.list_skill_candidates', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.explain', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.inspect_bundle', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.inspect_runtime_window', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.inspect_observability_dashboard', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.capture_observability_snapshot', surface: 'debug_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.inspect_observability_history', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.create_import_job', surface: 'debug_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.run_import_job', surface: 'debug_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.retry_import_job', surface: 'debug_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.rerun_import_job', surface: 'debug_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.schedule_import_job', surface: 'debug_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.run_due_import_jobs', surface: 'debug_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.get_import_job', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.list_import_jobs', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.list_import_job_history', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.apply_corrections', surface: 'debug_api', readonly: false, authority: 'runtime_plugin', directStoreAccess: false },
    { name: 'compact-context.list_corrections', surface: 'debug_api', readonly: true, authority: 'runtime_plugin', directStoreAccess: false }
];
export const CONTROL_PLANE_SERVICE_BOUNDARY = [
    { name: 'governance-service', surface: 'control_plane_service', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'observability-service', surface: 'control_plane_service', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'import-service', surface: 'control_plane_service', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'extension-registry', surface: 'control_plane_service', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'autonomy-service', surface: 'control_plane_service', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'workspace-catalog-service', surface: 'control_plane_service', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'platform-event-service', surface: 'control_plane_service', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'control-plane-facade', surface: 'control_plane_service', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'importer-registry', surface: 'control_plane_service', readonly: true, authority: 'control_plane_service', directStoreAccess: false }
];
export const CONTROL_PLANE_API_BOUNDARY = [
    { name: 'GET /api/health', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/runtime/snapshots', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/runtime/explain', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/governance/proposals', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/governance/audit', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/governance/templates', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/governance/global/review', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/governance/global/recovery', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/governance/lifecycle-policies', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/governance/lifecycle-policies', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/governance/proposals/bulk-rollback', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/governance/preview', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/governance/conflicts', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/governance/proposals', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/governance/proposals/batch', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/governance/proposals/batch/review', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/governance/proposals/batch/rollback', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/governance/proposals/:id/review', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/governance/proposals/:id/apply', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/governance/proposals/:id/rollback', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/observability/dashboard', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/observability/snapshots', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/observability/history', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/observability/history/page', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/observability/thresholds', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/observability/thresholds', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/observability/subscriptions', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/observability/subscriptions', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/observability/notifications', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/observability/compare', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/import/catalog', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/import/jobs', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/import/jobs/:id', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/import/jobs/:id/history', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/import/jobs', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/import/jobs/:id/run', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/import/jobs/:id/retry', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/import/jobs/:id/rerun', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/import/jobs/:id/schedule', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/import/jobs/batch/run', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/import/jobs/batch/stop', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/import/jobs/batch/resume', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/import/dead-letters', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/workbench/aliases', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/workbench/knowledge-review', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/workbench/import-review', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/workbench/runtime-governance-trace', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/extensions', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/extensions', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/extensions/negotiate', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/autonomy/recommendations', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/autonomy/simulate', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/workspaces', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/workspaces/:id', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/workspaces/aggregate', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/workspaces/policies', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/workspaces/policies', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/platform/events', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/platform/events/stream', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/platform/webhooks/subscriptions', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'POST /api/platform/webhooks/subscriptions', surface: 'control_plane_api', readonly: false, authority: 'control_plane_service', directStoreAccess: false },
    { name: 'GET /api/platform/webhooks/deliveries', surface: 'control_plane_api', readonly: true, authority: 'control_plane_service', directStoreAccess: false }
];
export const CONTROL_PLANE_READONLY_SOURCES = [
    'live_runtime_snapshot',
    'persisted_runtime_snapshot',
    'transcript_session_file'
];
export const DEFAULT_OBSERVABILITY_ALERT_THRESHOLDS = {
    minLiveRuntimeRatio: 0.5,
    maxTranscriptFallbackRatio: 0.4,
    maxRecallNoiseRate: 0.35,
    minPromotionQuality: 0.6,
    maxKnowledgePollutionRate: 0.2,
    minHighScopeReuseBenefit: 0.4,
    maxHighScopeReuseIntrusion: 0.3,
    minMultiSourceCoverage: 0.5
};
export const DEFAULT_IMPORT_SCHEDULER_POLICY = {
    maxRetryCount: 3,
    initialBackoffMs: 60_000,
    maxBackoffMs: 3_600_000,
    deadLetterAfterRetryCount: 3,
    historyRetentionLimit: 50
};
